GET http://web-scraping-nh.herokuapp.com/example/DRAGONBALL HTTP/1.1

###

POST http://web-scraping-nh.herokuapp.com/example/ HTTP/1.1
content-type: application/json

{
    "name": "YIYO2",
    "total": 11
}